version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - minio
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/imagerecognition
      - MINIO_ENDPOINT=minio:9999
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    volumes:
      - ./backend:/app

  nginx:
    build: ./nginx
    ports:
      - "8888:80"
    depends_on:
      - frontend
      - backend

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=imagerecognition
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    ports:
      - "9999:9999"
      - "9998:9998"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9998" --address ":9999"

volumes:
  postgres_data:
  minio_data: 