apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-recognition
  namespace: openfaas-fn
  labels:
    app: image-recognition
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-recognition
  template:
    metadata:
      labels:
        app: image-recognition
    spec:
      containers:
      - name: image-recognition
        image: ${DOCKER_REGISTRY}/image-recognition-function:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "1000m"
            memory: "2Gi"
          requests:
            cpu: "500m"
            memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: image-recognition
  namespace: openfaas-fn
spec:
  selector:
    app: image-recognition
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP 