apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: openfaas/gateway:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: functions_provider_url
          value: "http://faas-kubernetes:8080/"
        - name: read_timeout
          value: "60s"
        - name: write_timeout
          value: "60s"
        - name: upstream_timeout
          value: "65s"
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: faas-kubernetes
  labels:
    app: faas-kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faas-kubernetes
  template:
    metadata:
      labels:
        app: faas-kubernetes
    spec:
      serviceAccountName: openfaas-controller
      containers:
      - name: faas-kubernetes
        image: openfaas/faas-netes:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: function_namespace
          value: "openfaas-fn"
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: faas-kubernetes
spec:
  selector:
    app: faas-kubernetes
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openfaas-controller
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openfaas-role
  namespace: openfaas-fn
rules:
- apiGroups: [""]
  resources: ["pods", "services", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps", "extensions"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openfaas-role-binding
  namespace: openfaas-fn
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openfaas-role
subjects:
- kind: ServiceAccount
  name: openfaas-controller
  namespace: default
---
apiVersion: v1
kind: Namespace
metadata:
  name: openfaas-fn 